name: Maven Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  dependency-submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run Maven Build
        run: mvn clean install

      - name: Submit Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
